import Head from 'next/head'
import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import Main from '@/components/Main'
import About from '@/components/About'
import Skills from '@/components/Skills'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>William Locke | Online Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Main />
      <About />
      <Skills />
    </>
  )
}
